<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net4.7.2</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Reporting.Core" Version="24.2.7" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\CustomControls.Design\CustomControls.Design.csproj" />
    <ProjectReference Include="..\..\CustomControls.RoundedControls\CustomControls.RoundedControls.csproj" />
    <ProjectReference Include="..\..\CustomControls.SwissQRBill\CustomControls.SwissQRBill.csproj" />
  </ItemGroup>
</Project>
